name: Build and Release Windows, Linux, and macOS

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g. 1.0.0)'
        required: false
        default: ''

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            VERSION=$(node -p "require('./package.json').version")
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          gh release create v$VERSION \
            --draft \
            --title "KI-Assistant v$VERSION" \
            --generate-notes

  build-windows:
    name: Build Windows
    needs: release
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update version
        run: |
          node -e "const fs = require('fs'); const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8')); pkg.version = '${{ needs.release.outputs.version }}'; fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));"

      - name: Build Windows app
        run: |
          npm run build:win
          dir dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Windows artifacts
        run: |
          $exeFile = Get-ChildItem -Path dist -Recurse -Include "*.exe" | Select-Object -First 1

          if ($exeFile) {
            mkdir -p output
            Copy-Item $exeFile.FullName -Destination "output/KI-Assistant-Setup-${{ needs.release.outputs.version }}.exe"
          } else {
            Write-Error "No executable found in dist directory"
            exit 1
          }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: KI-Assistant-Setup-${{ needs.release.outputs.version }}
          path: output

      - name: Delete existing asset
        run: |
          gh release delete "v$VERSION" --yes --asset "KI-Assistant-Setup-${{ needs.release.outputs.version }}.exe" || echo "No existing asset to delete"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VERSION: ${{ needs.release.outputs.version }}

      - name: Upload release asset
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VERSION: ${{ needs.release.outputs.version }}
        run: |
          $assetPath = "output/KI-Assistant-Setup-$env:VERSION.exe"
          if (Test-Path $assetPath) {
            echo "Uploading $assetPath to release..."
            gh release upload "v$env:VERSION" "$assetPath"
          } else {
            echo "Error: Asset not found at $assetPath"
            exit 1
          }

  build-linux:
    name: Build Linux
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update version
        run: |
          node -e "const fs = require('fs'); const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8')); pkg.version = '${{ needs.release.outputs.version }}'; fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));"

      - name: Build Linux app
        run: |
          npm run build:linux
          ls dist

      - name: Package Linux artifacts
        run: |
          mkdir -p output
          cp dist/*.AppImage output/KI-Assistant-${{ needs.release.outputs.version }}.AppImage

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: KI-Assistant-${{ needs.release.outputs.version }}.AppImage
          path: output

  build-macos:
    name: Build macOS
    needs: release
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update version
        run: |
          node -e "const fs = require('fs'); const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8')); pkg.version = '${{ needs.release.outputs.version }}'; fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));"

      - name: Build macOS app
        run: |
          npm run build:mac
          ls dist

      - name: Package macOS artifacts
        run: |
          mkdir -p output
          cp dist/*.dmg output/KI-Assistant-${{ needs.release.outputs.version }}.dmg

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: KI-Assistant-${{ needs.release.outputs.version }}.dmg
          path: output

  finalize:
    name: Finalize Release
    needs: [ release, build-windows, build-linux, build-macos ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Finalize release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VERSION: ${{ needs.release.outputs.version }}
        run: |
          gh release edit v$VERSION --draft=false
          echo "Please edit the draft release on GitHub to add release notes and publish."
