name: Build and Release Windows

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g. 1.0.0)'
        required: true
        default: ''

# Explizite Berechtigungen hinzufügen
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          gh release create v$VERSION \
            --draft \
            --title "KI-Assistant v$VERSION" \
            --notes "KI-Assistant Version $VERSION
          
            ## Download
          
            - Windows: KI-Assistant-Setup-$VERSION.exe"

  build-windows:
    name: Build Windows
    needs: release
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update version
        run: |
          npm version ${{ needs.release.outputs.version }} --no-git-tag-version

      # Build the app for Windows
      - name: Build Windows app
        run: npm run build:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Package artifacts
      - name: Package Windows artifacts
        run: |
          mkdir -p output
          cp "dist/KI-Assistant-Setup-${{ needs.release.outputs.version }}.exe" output/

      # Upload build artifacts to GitHub
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: KI-Assistant-Setup-${{ needs.release.outputs.version }}
          path: output

      # Upload to release using the gh cli
      - name: Upload release asset
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ needs.release.outputs.version }}
        run: |
          $assetPath = "output/KI-Assistant-Setup-$env:VERSION.exe"
          if (Test-Path $assetPath) {
            echo "Uploading $assetPath to release..."
            gh release upload "v$env:VERSION" "$assetPath"
          } else {
            echo "Error: Asset not found at $assetPath"
            exit 1
          }

  # Final job to mark release as ready
  finalize:
    name: Finalize Release
    needs: [ release, build-windows ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Finalize release
        run: |
          echo "Release build complete: ${{ needs.release.outputs.version }}"
          echo "Please edit the draft release on GitHub to add release notes and publish."